# Generated by Django 4.1.5 on 2023-01-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer', models.TimeField(max_length=6, verbose_name='time')),
                ('periodicity', models.CharField(choices=[('day', 'Once a day'), ('weak', 'Once a weak'), ('month', 'Once a month')], max_length=9)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('created', 'Created'), ('started', 'Started')], default='created', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('body', models.TextField(max_length=2000, verbose_name='Message body')),
            ],
        ),
    ]
