# Generated by Django 4.1.5 on 2023-01-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='recipients',
            field=models.ManyToManyField(blank=True, null=True, to='mailer.recipient', verbose_name='recipients'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='periodicity',
            field=models.CharField(choices=[('daily', 'Once a day'), ('weakly', 'Once a weak'), ('monthly', 'Once a month')], max_length=9),
        ),
    ]
