# Generated by Django 4.1.5 on 2023-01-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='recipients',
            field=models.ManyToManyField(to='mailer.recipient', verbose_name='recipients'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='address',
            field=models.EmailField(max_length=254),
        ),
    ]
