# Generated by Django 4.1.5 on 2023-01-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0006_alter_distribution_recipients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='messages',
            field=models.ManyToManyField(to='mailer.message', verbose_name='messages'),
        ),
    ]
